jobs:
    build-job:
       docker:
         - image: node
       steps:
         - run: npm i

    deploy-job:
       docker:
         - image: node
       steps:
         - run: npm i
         - run:
             name: Deploy Master to Firebase
             command: ./node_modules/.bin/firebase deploy --token=1/-BYQ7e2D-J0Ldjhh9aipCo1GgwUxEWuPcxKEr-ZaMT4



workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
          only: master
